name: Plex Dupefinder

on:
  schedule:
    - cron: '0 19 * * 0'
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Echo hello world
        run: echo "hello world"
